services:
  nginx:
    container_name: nginx
    build: 
      context: ./frontend/
      dockerfile: Dockerfile
    volumes: 
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./mime.types:/etc/nginx/mime.types
    ports: 
        - 80:80
    depends_on:
        - backend
  backend:
    container_name: backend
    restart: always
    command: node ./dist/main.js
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
        - 8080:8080
