services:
  nginx:
    container_name: nginx
    image: nginx
    volumes: 
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./mime.types:/etc/nginx/mime.types
        - ./frontend/dist:/var/www/html/
    ports: 
        - 80:80
        - 443:443
    depends_on:
        - backend
  backend:
    container_name: backend
    restart: always
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
        - 8081:8080
